app/controllers/admin/missions_controller.rb
lib/tasks/dev.rake

mission的fake file 
使用ffaker::book
5 個邀請數
@Cronobow  @eggyy1224

add fake rake: fake_mission in dev.rake

---

app/views/layouts/_navbar.html.erb
app/views/layouts/_notice.html.erb
app/views/layouts/application.html.erb

What & Why?
---
1. update layout application
---
localhost

update layout application

---

.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/users.coffee
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/user.rb
app/uploaders/avatar_uploader.rb
app/views/users/edit.html.erb
app/views/users/show.html.erb
config/routes.rb
db/seeds.rb
lib/tasks/dev.rake
test/controllers/users_controller_test.rb

1. 更新dev:fake_user部分，使其可以用carrierwave上傳照片。
2. 將上傳照片相關的gem（carrierwave以及minimagic）加入，要在本地端先安裝imagemagick gem才能使用minimagic。
3. 新增user的show以及edit頁面，目前已經可以做初步的瀏覽檔案以及編輯檔案的功能。

User profile

---

app/controllers/missions_controller.rb
app/views/layouts/_navbar.html.erb
test/integration/user_sign_up_test_test.rb

1.  在mission controller加入驗證
2. 將layout的navbar加入個人資料頁面之連結
3. 加入使用者註冊之測試

add sign up test

---

app/controllers/missions_controller.rb
app/views/layouts/_navbar.html.erb
test/controllers/admin/missions_controller_test.rb
test/fixtures/missions.yml
test/fixtures/users.yml
test/integration/admin_mission_crud_test.rb
test/integration/user_sign_up_test_test.rb

1. 加入後台任務測試用資料。
2. 加入後台crud 任務之測試。

Control panel mission crud test

---

app/controllers/missions_controller.rb
app/models/user.rb
db/schema.rb

修正錯誤
使用者可否執行任務的狀態為user.available
(之前打成user.state)
localhost
cc @Cronobow @eggyy1224

fix bug: user.available

---

app/assets/javascripts/instances.coffee
app/assets/stylesheets/instances.scss
app/controllers/instances_controller.rb
app/controllers/missions_controller.rb
app/helpers/instances_helper.rb
app/models/instance.rb
app/views/instances/_member_info.html.erb
app/views/instances/_mission_info.html.erb
app/views/instances/complete.html.erb
app/views/instances/in_progress.html.erb
app/views/instances/teaming.html.erb
config/routes.rb
test/controllers/instances_controller_test.rb

1.  本來將instance 路由放在 mission下面，後來覺得不需要那麼麻煩，就拿出來了
2. mission#challenge 後 
- 產生instance
- 導向instances#show
- instance.rb 內有 after_commit ,  檢查如果成員邀請滿了，就把狀態改為進行中(in_progress)
3. instances#show裡面，會依據不同的狀態（teaming, in_progress, complete）render不同的view
目前使用者可挑戰等級內的任務，如果滿一人自動將任務改為in_progress
cc @eggyy1224 @Cronobow

在任務中可以新增副本

---

app/controllers/instances_controller.rb
app/models/instance.rb
app/views/instances/complete.html.erb
app/views/instances/in_progress.html.erb
config/routes.rb
db/migrate/20180313143457_add_column_answer_in_instances.rb
db/schema.rb

在in_progress狀態的副本可以提交答案，
instance狀態會變成complete
members的狀態會變成 yes
1. 新增routes : submit_instance_path(instance) 
2.新增migration: add column "answer"  在instances中
3. instances#submit action
4. view修改, 加入 answer 欄位在in_progress的view裡面
cc. @Cronobow  @eggyy1224

提交副本（instance）

---

app/controllers/instances_controller.rb
app/models/instance.rb
app/views/instances/abort.html.erb
app/views/instances/in_progress.html.erb
app/views/instances/teaming.html.erb
config/routes.rb
db/migrate/20180314064128_remove_column_user_state.rb
db/schema.rb

Remove column user state

---

app/views/users/edit.html.erb
app/views/users/show.html.erb

修正刪除state後的view錯誤

---

app/assets/javascripts/invitations.coffee
app/assets/stylesheets/invitations.scss
app/controllers/instances_controller.rb
app/controllers/invitations_controller.rb
app/controllers/users_controller.rb
app/helpers/invitations_helper.rb
app/models/instance.rb
app/models/invitation.rb
app/models/user.rb
app/views/instances/_candidates_info.html.erb
app/views/instances/_inviting_users.html.erb
app/views/instances/teaming.html.erb
app/views/users/show.html.erb
config/routes.rb
lib/tasks/dev.rake
test/controllers/invitations_controller_test.rb

- 新增假資料: 測試用level 1 missions
- 新增method回傳可組隊的集合
- 使用者可以在副本頁面的組隊狀態中，送出邀請
使用者可送出邀請
- 新增invitation model
- 新增 route:  POST :invite_user_path, post :accept, decline, cancel
- 新增 invitation, user , instance的relationship
- 在invitation.rb中, 新增查詢受邀者相關的method
- 修改view顯示
如何送出邀請
1.  在teaming(instances#show)頁面，送出` post: invite_user(user)` , 夾帶`instance_id`參數
2. `instances#invite` 先確認有資格可接受邀請，然後新增invitation
3. redirect_to` instances#show`
可邀請名單, 邀請中名單
1. 在instances.rb 中 新增`invitable_users` 可回傳 所有可邀請user的array
2. 在instacne.rb中 新增`inviting_users` 可回傳所有邀請中user的array

Invite user

---

app/assets/javascripts/invitations.coffee
app/assets/stylesheets/invitations.scss
app/controllers/instances_controller.rb
app/controllers/invitations_controller.rb
app/controllers/users_controller.rb
app/helpers/invitations_helper.rb
app/models/instance.rb
app/models/invitation.rb
app/models/user.rb
app/views/instances/_candidates_info.html.erb
app/views/instances/_inviting_users.html.erb
app/views/instances/teaming.html.erb
app/views/users/show.html.erb
config/routes.rb
lib/tasks/dev.rake
test/controllers/invitations_controller_test.rb

邀請者可以取消副本(instance)中的邀請(invitation)
- 新增` inviting_invitation` method in instance.rb: 可以將狀態是inviting的invitation回傳
- 修改 instance#show: 為了配合邀請函, 使用 `instance.inviting_invitation` 來吐出受邀者的資訊
cc @Cronobow  @eggyy1224 
請先merge invite_user pr

Invite cancel

---

app/controllers/invitations_controller.rb
app/models/invitation.rb
app/views/instances/_inviting_users.html.erb
app/views/invitations/show.html.erb

- 顯示邀請函頁面
- 受邀者可以接受邀請 
- 新增invitation#show invitation#accept
- 在invitation.rb 中新增after_commit: 當接受邀請後，自動將受邀者加入instance.member

invitation#show, invitation#accept

---

app/controllers/invitations_controller.rb
app/controllers/users_controller.rb
app/models/instance.rb
test/controllers/invitations_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/instances.yml
test/fixtures/invitations.yml
test/fixtures/missions.yml
test/fixtures/user_instances.yml
test/fixtures/users.yml
test/integration/user_can_invite_others_test.rb

1. 在invitation#cancel加入驗證。修改invitation controller一些錯誤。
2. 完成邀請功能的測試模組。

invitation測試完成

---

app/controllers/invitations_controller.rb

- invitation 所有action的訪問限制
- DRY the code 
- 新增三個before_action

邀請函只有邀請者和受邀者可以瀏覽

---

app/assets/stylesheets/style.scss
app/controllers/users_controller.rb
app/views/instances/_member_info.html.erb
app/views/instances/_teaming.html.erb
app/views/shared/_user_card.html.erb
app/views/users/index.html.erb

What & Why?
---
1. Update user card
---
localhost

Update user card

---

app/controllers/missions_controller.rb
app/models/instance.rb
app/models/user.rb

- user 設定user.available只控制要不要接受邀請
- 關閉邀請不會影響進行中的邀請函 任務
- 關閉邀請還是可以發起挑戰新任務
- user.take_mission?  修改只限定等級判斷條件
- instance.rb:  副本狀態不影響user state
- mission#challenge:  挑戰副本不會更改user.state

modify user.availabe check: cancel busy state

---

app/controllers/missions_controller.rb
app/helpers/users_helper.rb
app/models/instance.rb
app/models/user.rb
app/views/users/edit.html.erb
app/views/users/show.html.erb
db/migrate/20180318084558_change_column_user_available.rb
db/schema.rb

更改user available的型態為boolean
- 新增migration, 有資料轉換型別不會....所以用刪除新增的方式
- 修改有使用user available的地方
- user edit show的部分：改成 邀請信箱 開啟 關閉

更改user available 的型態為boolean

---

app/controllers/instances_controller.rb

副本只有member可以瀏覽
- 重構程式碼
- 副本只有member可瀏覽
cc @Cronobow @eggyy1224

副本只有member可以瀏覽

---

app/assets/javascripts/instance_msgs.coffee
app/assets/stylesheets/instance_msgs.scss
app/controllers/instance_msgs_controller.rb
app/controllers/instances_controller.rb
app/helpers/instance_msgs_helper.rb
app/models/instance.rb
app/models/instance_msg.rb
app/views/instances/_leave_msg.html.erb
app/views/instances/_show_msgs.html.erb
app/views/instances/show.html.erb
config/routes.rb
test/controllers/instance_msgs_controller_test.rb

- 副本成員可以在instnace留言
- 只有進行中的任務可以留言
- 只有進行中 放棄 完成的副本可以瀏覽留言
- 新增 resources instance_msgs route
- 新增 instance_msgs#create
- 修改instance#show： 可以依照state條件顯示msgs 

副本成員可以在instance留言

---

app/controllers/users_controller.rb
app/models/instance.rb
test/controllers/instances_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/invitations.yml
test/fixtures/missions.yml
test/fixtures/users.yml
test/integration/user_can_abort_instance_and_submit_instance_test.rb
test/integration/user_can_view_missions_and_challenge_mission_test.rb

Modify tests

---

app/controllers/instances_controller.rb

修改instances#submit bug

---

app/assets/javascripts/reviews.coffee
app/assets/stylesheets/reviews.scss
app/controllers/instances_controller.rb
app/controllers/reviews_controller.rb
app/helpers/reviews_helper.rb
app/models/instance.rb
app/models/review.rb
app/models/user.rb
app/models/user_instance.rb
app/views/instances/_leave_review.html.erb
app/views/instances/review.html.erb
app/views/instances/show.html.erb
config/routes.rb
test/controllers/reviews_controller_test.rb

副本任務結束後(instnace.state == abort or complete)，使用者可以評論隊友
任務結束後，在instnace#show頁面可以看到隊友的評論
或者到instance#review頁面去評論隊友
- 修改routes
- 新增instances#reviews： 可以顯示評論，或者在這邊可輸入評論
- 新增reviews#create：新增評論
- review.rb scope：新增一些scope 可以找出指定的review
- user.rb method：新增一些method 判斷有沒有被某人評論過

副本任務結束後，可以評論隊友

---

app/controllers/invitations_controller.rb
app/helpers/invitations_helper.rb
app/models/mission.rb
app/views/invitations/_received_list.html.erb
app/views/invitations/_sent_list.html.erb
app/views/invitations/_show.html.erb
app/views/invitations/index.html.erb
app/views/invite_msgs/create.js.erb
app/views/shared/_msg_board.html.erb

What & Why?
---
1. Update invitation index
---
localhost

Update invitation index

---

app/controllers/instances_controller.rb
test/controllers/instances_controller_test.rb
test/controllers/invitations_controller_test.rb
test/controllers/missions_controller_test.rb
test/fixtures/instances.yml
test/fixtures/user_instances.yml
test/fixtures/users.yml
test/integration/instance_show_page_test.rb
test/integration/invatation_msgs_test.rb
test/integration/user_can_view_missions_and_challenge_mission_test.rb

1. 將測試修改成對應ajax的版本
2. instance controller review action的測試

Review tests

---

app/assets/javascripts/admin/instances.coffee
app/assets/stylesheets/admin/instances.scss
app/controllers/admin/instances_controller.rb
app/controllers/instances_controller.rb
app/helpers/admin/instances_helper.rb
app/helpers/instances_helper.rb
app/views/admin/instances/_instance_list.html.erb
app/views/admin/instances/index.html.erb
app/views/layouts/_admin_sidebar.html.erb
config/routes.rb
test/controllers/admin/instances_controller_test.rb
test/controllers/instances_controller_test.rb
test/controllers/invitations_controller_test.rb
test/controllers/missions_controller_test.rb
test/fixtures/instances.yml
test/fixtures/user_instances.yml
test/fixtures/users.yml
test/integration/instance_show_page_test.rb
test/integration/invatation_msgs_test.rb
test/integration/user_can_view_missions_and_challenge_mission_test.rb

Admin view instances

---

app/views/layouts/application.html.erb

What & Why?
---
1. fix turbolinks cache problem
---
localhost

Fix turbolinks cache problem

---

app/controllers/users_controller.rb
app/models/instance.rb
app/models/review.rb
app/models/user.rb
app/views/layouts/_sidebar.html.erb
app/views/missions/show.html.erb
app/views/users/show.html.erb

讓user show頁面可以顯示
- 完成過的任務
- 完成過的副本
- 使用者評價
- 尚未送出的評論
- review 中增加 scope: 篩選出已送出或尚未送出的reivew
- 復原mission/show.html.erb  

修改 user#show頁面

---

app/controllers/users_controller.rb
app/helpers/instances_helper.rb
app/models/user.rb
app/views/instances/_candidates_list.html.erb
app/views/instances/_invited_list.html.erb
app/views/instances/_member_list.html.erb
app/views/instances/show.html.erb
app/views/instances/state/_abort.html.erb
app/views/instances/state/_complete.html.erb
app/views/instances/state/_in_progress.html.erb
app/views/instances/state/_teaming.html.erb
app/views/shared/_user_card.html.erb
app/views/shared/_user_head.html.erb
app/views/users/_show_user.html.erb
app/views/users/show.html.erb
app/views/users/show.js.erb

What & Why?
---
1. 邀請畫面增加部分標示
2. 新增 送出/取消 邀請時，按鈕會 disable
3. 更新 任務邀請 的畫面
4. 增加 user show 的 ajax

Update instance show

---

app/controllers/instances_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/models/instance.rb
app/views/instances/_leave_review.html.erb
test/controllers/instances_controller_test.rb
test/controllers/missions_controller_test.rb
test/controllers/reviews_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/reviews.yml
test/integration/instance_show_page_test.rb
test/integration/user_can_abort_instance_and_submit_instance_test.rb
test/integration/user_can_invite_others_test.rb

1. 修改測試以符合ajax
2. 修改評價controller邏輯

Ajax review tests

---

.gitignore
Gemfile.lock
app/uploaders/avatar_uploader.rb
app/uploaders/mission_image_uploader.rb
config/database.yml
config/initializers/carrier_wave.rb
config/initializers/devise.rb
lib/tasks/dev.rake

1. 增加instances 假資料
2. 完成部署到heroku的設定
3. 完成AWS S3的設置

Fake data and deploy

---

app/controllers/invitations_controller.rb
app/views/instances/_msgs_board.html.erb
app/views/invitations/_received_list.html.erb
app/views/invitations/_sent_list.html.erb
app/views/invitations/_show.html.erb
app/views/invitations/index.html.erb
app/views/missions/_show_mission.html.erb

What & Why?
---
1. 修改部分介面呈現
2. 可以在邀請函列表中取消邀請
2. 增加邀請函列表中，點擊標題可以看到任務詳情
---
localhost

Update instance and invitation layout

---

config/email.yml
config/environments/production.rb

Mail production

---

config/initializers/carrier_wave.rb

fix s3 bug

---

app/controllers/instances_controller.rb
app/models/instance.rb
app/models/invitation.rb
app/views/instances/_ans_form.html.erb
app/views/instances/_ans_panel.html.erb
app/views/instances/_msgs_board.html.erb
app/views/instances/edit.js.erb
app/views/instances/save.js.erb
app/views/instances/state/_abort.html.erb
app/views/instances/state/_complete.html.erb
app/views/instances/state/_in_progress.html.erb
app/views/invitations/_show.html.erb
app/views/invitations/show.js.erb
config/application.rb
config/routes.rb
db/migrate/20180323025749_add_modifier_to_instances.rb
db/schema.rb

- 可以在instance #show   畫面 看到提交任務  放棄任務 儲存答案的人
- 新增migration add column modifier
- 在abort compete save action下面 設定modifier
cc @Cronobow @eggyy1224   記得migrate

在instances增加modifier, 可以顯示最後修改的人

---

app/controllers/instances_controller.rb
app/views/instances/_ans_form.html.erb
test/fixtures/instances.yml
test/integration/instance_show_page_test.rb
test/integration/user_can_abort_instance_and_submit_instance_test.rb

新增副本儲存與編輯的測試

---

app/controllers/admin/missions_controller.rb
app/views/admin/missions/_form.html.erb
app/views/admin/missions/show.html.erb

admin page 可以編輯xp
cc @Cronobow @eggyy1224

admin page 可以編輯xp

---

Gemfile.lock
app/controllers/admin/missions_controller.rb
app/views/admin/missions/_mission_list.html.erb
lib/tasks/dev.rake
test/controllers/users_controller_test.rb
test/fixtures/users.yml
test/integration/user_can_abort_instance_and_submit_instance_test.rb

1. 修改版面改變所對應的測試
2. 新增經驗值相關測試
3. 修改dev:fake_instance

Fix test an add xp test

---

Gemfile.lock
app/assets/javascripts/followships.coffee
app/assets/stylesheets/followships.scss
app/controllers/admin/missions_controller.rb
app/controllers/followships_controller.rb
app/controllers/users_controller.rb
app/helpers/followships_helper.rb
app/models/followship.rb
app/models/user.rb
app/views/admin/missions/_mission_list.html.erb
app/views/shared/_follow.html.erb
app/views/users/_show_user.html.erb
app/views/users/_user_nav.html.erb
app/views/users/index.html.erb
config/routes.rb
db/migrate/20180325074033_create_followships.rb
db/migrate/20180325081216_user_add_following_followers_count.rb
db/schema.rb
lib/tasks/dev.rake
test/controllers/followships_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/followships.yml
test/fixtures/users.yml
test/integration/user_can_abort_instance_and_submit_instance_test.rb
test/integration/user_can_follow_and_unfollow_other_users_test.rb
test/models/followship_test.rb

1. 完成user追蹤功能，可以依照路徑在user/index看到不同的使用者顯示
2. 完成追蹤功能的測試

Follow user

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/notification.js
app/assets/javascripts/notifications.coffee
app/assets/stylesheets/base.css.scss
app/assets/stylesheets/notifications.scss
app/controllers/notifications_controller.rb
app/helpers/notifications_helper.rb
app/models/invite_msg.rb
app/models/notification.rb
app/models/user.rb
app/views/invitations/show.html.erb
app/views/invitations/show.js.erb
app/views/layouts/_navbar.html.erb
app/views/notifications/index.json.jbuilder
app/views/notifications/invite_msgs/_send_msg.html.erb
app/views/notifications/shared/_notification_item.html.erb
config/routes.rb
db/migrate/20180324155853_create_notifications.rb
db/schema.rb
test/controllers/notifications_controller_test.rb
test/fixtures/notifications.yml
test/models/notification_test.rb

新增通知功能
目前只有invite_msg create的時候會產生通知
算是陽春版通知，之後會再加上去
- 增加notification model
- 在invite_msg after_create之後，會產生一筆通知
- 使用ajax 把notification 接到前端

新增通知 - invite_msg

---

app/controllers/missions_controller.rb
app/views/missions/index.html.erb
app/views/users/_show_user.html.erb
config/routes.rb
db/schema.rb
test/fixtures/missions.yml
test/integration/can_invite_user_for_mission_from_users_list_test.rb

1. 加入可以從user清單選擇隊友一起解任務的功能。
2. 新增相關測試。

Teaming from user

---

app/controllers/instances_controller.rb
app/controllers/missions_controller.rb
app/controllers/users_controller.rb
app/views/missions/index.html.erb
app/views/users/_show_user.html.erb
app/views/users/_users_list.html.erb
app/views/users/index.html.erb
app/views/users/index.js.erb
config/routes.rb
db/schema.rb
test/fixtures/missions.yml
test/integration/can_invite_user_for_mission_from_users_list_test.rb

Filter user function

---

app/assets/javascripts/angle/modules/common/localize.js
app/assets/javascripts/notification.js
app/assets/stylesheets/style.scss
app/controllers/notifications_controller.rb
app/models/invite_msg.rb
app/models/notification.rb
app/views/invitations/show.html.erb
app/views/layouts/_navbar.html.erb
app/views/notifications/index.html.erb
app/views/notifications/index.json.jbuilder
app/views/notifications/invite_msgs/_send_msg.html.erb
app/views/notifications/shared/_notification_item.html.erb
config/routes.rb
db/migrate/20180326055613_add_check_at_in_notifications.rb
db/schema.rb

- 顯示avatar
- 樣式調整
- 當有多則invite_msgs時，刪掉舊的通知

修改通知：顯示avatar ，刪除重複的invite_msgs

---

test/integration/user_index_test_test.rb

Fix test bug

---

app/controllers/users_controller.rb
app/helpers/instances_helper.rb
app/views/instances/_ans_panel.html.erb
app/views/layouts/_sidebar.html.erb
app/views/missions/index.html.erb
app/views/shared/_follow.html.erb
app/views/shared/_user_card.html.erb
app/views/users/_show_user.html.erb
app/views/users/_user_nav.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

What & Why?
---
1. 更新 user show / edit 頁面
2. 更新部分用字
---
localhost

Update user view

---

.gitignore
Gemfile
Gemfile.lock
config/initializers/devise.rb
test/fixtures/missions.yml
test/integration/can_invite_user_for_mission_from_users_list_test.rb

加入figaro gem處理環境變數
```$bundle```
```$ bundle exec figaro install```
會產生config/application.yml檔案，此檔案會加進.gitignore
在config/application.yml內加入
```
GITHUB_KEY: 44abc175dcf17950c42a
GITHUB_SECRET: 62a4c367c6773b733d9613cf15bee859f31a4b02
```
就可以在本地端環境隨時取用想要的環境變數！ex: ENV['GITHUB_KEY']

加入figaro gem處理環境變數

---

app/controllers/confirmations_controller.rb
config/routes.rb

電子信箱註冊後直接登入功能

---

app/helpers/users_helper.rb
app/views/shared/_user_card.html.erb
test/controllers/missions_controller_test.rb
test/integration/instance_show_page_test.rb

1. 修正錯誤測試錯誤
2. 新增helper method
3. 修改大頭貼相關的view
instance/show頁面使用者圖片跑版
@Cronobow 再拜託修一下

修正錯誤測試錯誤、新增helper method、修改大頭貼相關的view

---

config/environments/production.rb
db/seeds.rb
lib/tasks/dev.rake

修正要deploy的bug
目前已上線，大家可以試看看功能是不是一切正常
https://pacific-dawn-73107.herokuapp.com/

Fix deploy bug

---

app/assets/stylesheets/style.scss
app/controllers/reviews_controller.rb
app/helpers/reviews_helper.rb
app/models/review.rb
app/views/instances/_leave_review.html.erb
app/views/shared/_review_card.html.erb
db/migrate/20180328074123_add_rating_in_reviews.rb
db/schema.rb

任務完成後，可以給使用者rating stars
- reviews 增加rating column
- 可以加上星星評分
- instance可以顯示星星評分
記得db:migrate

Rating star

---

app/assets/stylesheets/style.scss
app/controllers/users_controller.rb
app/helpers/reviews_helper.rb
app/models/review.rb
app/models/user.rb
app/views/instances/_leave_review.html.erb
app/views/shared/_review_card.html.erb
app/views/shared/_user_rating.html.erb
app/views/users/show.html.erb

- 個人頁面顯示 平均rating
- 增加了一個partial shared/_user_rating.html
- 加了一些css在 style.css
- 加了一些method 在user.rb，為了計算rating
之後應該會改寫用counter cache

在個人頁面顯示平均rating

---

app/helpers/users_helper.rb
db/seeds.rb
lib/tasks/dev.rake
test/integration/mission_index_test_test.rb
test/integration/user_index_test_test.rb
test/test_helper.rb

1. 修改測試報告格式。
2. fix部分測試內容。
3. 新增dev:fake_all方法, 一鍵重設所有假資料。
4. 顯示人頭user的大頭照

修改測試報告格式。fix部分測試內容

---

app/models/user.rb
app/views/shared/_user_rating.html.erb

fix user rating bug

---

app/models/user.rb

fix level bug

---

app/views/instances/_mission_info.html.erb
app/views/invitations/show.html.erb
app/views/shared/_user_card.html.erb

What & Why?
---
1. add mission info to  invitaion html view
---
localhost

add mission info to  invitaion html view

---

app/models/user.rb

名字預設為github上的名字

---

app/controllers/missions_controller.rb
app/views/layouts/_sidebar.html.erb
app/views/missions/dashboard.html.erb
config/routes.rb

What & Why?
---
1. 移除 mission#my_mission 改成 dashboard
2. 調整 sidebar
---
localhost

add dashboard path

---

app/assets/javascripts/recruit_boards.coffee
app/assets/stylesheets/recruit_boards.scss
app/controllers/recruit_boards_controller.rb
app/helpers/recruit_boards_helper.rb
app/models/instance.rb
app/models/invitation.rb
app/models/recruit_board.rb
app/models/user.rb
app/views/instances/show.html.erb
app/views/recruit_boards/index.html.erb
app/views/shared/_recruit_board_card.html.erb
config/routes.rb
db/migrate/20180329084313_create_recruit_boards.rb
db/migrate/20180329085928_add_available_to_recruit_board.rb
db/schema.rb
test/controllers/recruit_boards_controller_test.rb
test/fixtures/instances.yml
test/fixtures/missions.yml
test/fixtures/recruit_boards.yml
test/fixtures/user_instances.yml
test/integration/recruit_detective_test.rb
test/models/recruit_board_test.rb

1. 新增招募功能。
2. 招募功能相關驗證。
3. 招募功能相關測試。
在副本在副本頁面可以看到緊急招募按鈕，點擊之後會導向所有招募任務的頁面
所有招募任務頁面  

Board feature debut

---

app/controllers/missions_controller.rb
app/helpers/missions_helper.rb
app/models/instance.rb
app/models/user.rb
db/schema.rb
test/fixtures/instances.yml
test/fixtures/missions.yml
test/integration/user_can_view_missions_and_challenge_mission_test.rb

1. 發起者無法再發起同樣的任務功能
2. 關於此功能前端頁面小修改
3. 相關測試修改與新增

Cannot challenge a mission when self initiated and in progress

---

app/assets/javascripts/angle/modules/charts/easypiechart.js
app/assets/javascripts/angle/modules/charts/jquery.easypiechart.js
app/assets/stylesheets/style.scss
app/views/missions/dashboard.html.erb
db/schema.rb

戰情中心layout
各區塊規劃功能可參考quip
另外css我有小修一下
沒改太多，詳情請洽 `style.scss`
cc @Cronobow @eggyy1224

戰情中心layout

---

app/assets/javascripts/angle/modules/charts/easypiechart.js
app/assets/javascripts/angle/modules/charts/jquery.easypiechart.js
app/assets/stylesheets/style.scss
app/views/missions/dashboard.html.erb
db/schema.rb
lib/tasks/dev.rake

產生 2人以上任務的假副本和假review
@Cronobow  @eggyy1224

假資料：instance 和 reviews

---

app/models/followship.rb
lib/tasks/dev.rake

1. 追蹤功能驗證。
2. 修改假資料產生程式碼。用dev:fake_all指令會先清空資料庫。

新增追蹤驗證。修改假資料產生相關程式碼

---

app/controllers/application_controller.rb
app/controllers/instances_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/instances/state/_teaming.html.erb
app/views/shared/_filterrific_user_form.html.erb
app/views/users/index.html.erb
config/locales/zh-TW.yml


What & Why?
---
1. 修正其他的 user filter
2. 增加追蹤的人與被追蹤的人
---
localhost

update user filter

---

app/controllers/application_controller.rb
app/controllers/recruit_boards_controller.rb
app/views/instances/history.html.erb
app/views/instances/show.html.erb
app/views/instances/state/_teaming.html.erb
app/views/invitations/index.html.erb
app/views/invitations/sent_index.html.erb
app/views/invitations/show.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/_right_sidebar.html.erb
app/views/missions/dashboard.html.erb
app/views/missions/index.html.erb
app/views/missions/show.html.erb
app/views/notifications/index.html.erb
app/views/recruit_boards/index.html.erb
app/views/shared/_recruit_board_card.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
db/schema.rb
vendor/assets/stylesheets/angle/app/common/variables.scss
vendor/assets/stylesheets/angle/app/layout/offsidebar.scss

What & Why?
---
1. 增加右側招募看板
---
localhost

add recruit sidebar

---

config/email.yml
config/environments/production.rb
db/schema.rb

Domain config setting

---

app/controllers/application_controller.rb

What & Why?
---
1. add recruit order
---
localhost

add recruit order

---

app/assets/stylesheets/style.scss
app/views/missions/dashboard.html.erb

dashboard scroll bar

---

app/controllers/callbacks_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/edit.html.erb
config/initializers/devise.rb
db/schema.rb
test/integration/recruit_detective_test.rb

Login and mail bugs

---

app/assets/stylesheets/style.scss
app/controllers/admin/missions_controller.rb
app/views/missions/dashboard.html.erb

修正新增mission時，tag_list無法寫入的錯誤

---

app/assets/javascripts/angle/modules/charts/jquery.flot.categories.js
app/assets/javascripts/angle/modules/charts/jquery.flot.js
app/assets/javascripts/angle/modules/charts/jquery.flot.pie.js
app/assets/javascripts/angle/modules/charts/jquery.flot.resize.js
app/assets/javascripts/angle/modules/charts/jquery.flot.time.js
app/assets/javascripts/angle/modules/charts/jquery.flot.tooltip.js
app/assets/javascripts/angle/modules/charts/jquery.sparkline.js
app/controllers/users_controller.rb
app/views/users/show.html.erb

顯示user tag chart
貼在 quip 可能要討論固定哪些tag

顯示user tag chart

---

app/assets/javascripts/angle/modules/charts/jquery.flot.categories.js
app/assets/javascripts/angle/modules/charts/jquery.flot.js
app/assets/javascripts/angle/modules/charts/jquery.flot.pie.js
app/assets/javascripts/angle/modules/charts/jquery.flot.resize.js
app/assets/javascripts/angle/modules/charts/jquery.flot.time.js
app/assets/javascripts/angle/modules/charts/jquery.flot.tooltip.js
app/assets/javascripts/angle/modules/charts/jquery.sparkline.js
app/controllers/missions_controller.rb
app/controllers/users_controller.rb
app/views/missions/dashboard.html.erb
app/views/users/show.html.erb

顯示推薦任務
根據使用者有挑戰過的tag 亂數選出
然後挑出一樣tags的mission
mission是等級符合current_user，亂數挑出的
@Cronobow  @eggyy1224

戰情中心：顯示推薦任務

---

config/cable.yml
config/environments/production.rb

action cable上線設定

---

app/controllers/application_controller.rb
app/controllers/missions_controller.rb
app/models/mission.rb
app/views/instances/_leave_review.html.erb
app/views/missions/_missions_list.html.erb
app/views/missions/index.html.erb
app/views/missions/index.js.erb

What & Why?
---
1. 進入未評價 instance show ，評價區塊會跳動引導視覺動線
2. 新增 mission 篩選
---
localhost

Update mission filter

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/invite_msgs.js
app/assets/javascripts/channels/notifications.js
app/assets/javascripts/notification.js
app/channels/invite_msgs_channel.rb
app/controllers/invite_msgs_controller.rb
app/jobs/invite_msgs_relay_job.rb
app/models/invite_msg.rb
app/views/invitations/_invite_msg_board.html.erb
app/views/invitations/_invite_msg_show.html.erb
app/views/invitations/_show.html.erb
app/views/invitations/index.html.erb
app/views/invitations/sent_index.html.erb
app/views/invitations/show.html.erb
app/views/invite_msgs/create.js.erb
config/routes.rb
test/jobs/invite_msgs_relay_job_test.rb

修正錯誤
沒有訊息的邀請函在invitation#index invitation#show_index會出現錯誤

Fix bug invitation index

---

app/assets/javascripts/cable.js
app/assets/javascripts/channels/invite_msgs.js
app/assets/javascripts/channels/notifications.js
app/assets/javascripts/notification.js
app/channels/invite_msgs_channel.rb
app/controllers/invite_msgs_controller.rb
app/jobs/invite_msgs_relay_job.rb
app/models/invite_msg.rb
app/views/invitations/_invite_msg_board.html.erb
app/views/invitations/_invite_msg_show.html.erb
app/views/invitations/_show.html.erb
app/views/invitations/index.html.erb
app/views/invitations/sent_index.html.erb
app/views/invitations/show.html.erb
app/views/invite_msgs/create.js.erb
app/views/notifications/invitations/_accept.html.erb
config/routes.rb
test/jobs/invite_msgs_relay_job_test.rb

Invitation notification fix

---

app/assets/javascripts/channels/invite_msgs.js
app/controllers/invitations_controller.rb
app/controllers/invite_msgs_controller.rb
app/models/invitation.rb
app/models/invite_msg.rb
app/models/user.rb
app/views/invitations/_show.html.erb
app/views/invitations/index.html.erb
app/views/invitations/sent_index.html.erb
app/views/invitations/show.html.erb
app/views/layouts/_sidebar.html.erb
config/routes.rb
db/migrate/20180406154616_add_read_at_column_on_invite_msg.rb
db/schema.rb
lib/tasks/dev.rake

Unread msg

---

README.md
db/schema.rb

Modify read me

---

app/views/instances/_mission_info.html.erb
lib/tasks/dev.rake

- 為了修改mission假資料，新增一個rake來餵資料，後續會再修改
- 任務進行中因為description都擠在右邊，做一個任務詳情的按鈕
@Cronobow  @eggyy1224

假資料的rake, 任務詳情

---

app/views/instances/_mission_info.html.erb
lib/tasks/dev.rake
lib/tasks/mission.rake

新增一個rake task 
大家可以把假資料放進去試試看有沒有錯
請下`rails mission:mission_fake`
@Cronobow @eggyy1224

Mission fake

---

app/models/user.rb

修改github username找不到或者為空字串的bug

修改github username找不到或者為空字串的bug

---

app/models/user.rb
db/migrate/20180409123634_add_index_to_database.rb
db/migrate/20180409132433_add_user_instance_index.rb
db/schema.rb
test/integration/user_can_invite_others_test.rb

Database add index

---

lib/tasks/mission.rake

新增level1~4假任務

---

lib/tasks/mission.rake

What & Why?
---
1. 我把前三個L1 任務改成單人任務
2. 標題調整了一下
3. 加了一個快速通關任務
---
localhost

update fake mission

---

app/views/users/show.html.erb
db/schema.rb

使用者如果沒有任何任務，修正chart顯示
還是會顯示一張圓餅圖
@Cronobow @eggyy1224

使用者如果沒有任何任務，修正chart顯示

---

app/controllers/application_controller.rb
app/controllers/followships_controller.rb
app/controllers/instance_msgs_controller.rb
app/controllers/instances_controller.rb
app/controllers/invitations_controller.rb
app/controllers/invite_msgs_controller.rb
app/controllers/missions_controller.rb
app/controllers/notifications_controller.rb
app/controllers/public_controller.rb
app/controllers/recruit_boards_controller.rb
app/controllers/reviews_controller.rb
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/models/user.rb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/shared/_filterrific_user_form.html.erb
app/views/users/edit.html.erb

What & Why?
---
1. 修正 footer
2. 調整 authenticate_user! 位置
3. 增加 location filter
---
localhost

Update user show

---

db/schema.rb
lib/tasks/dev.rake

Modify dev fake

---

app/views/shared/_user_card.html.erb
app/views/users/_show_user.html.erb

What & Why?
---
1. 修正頭像變形
---
localhost

fix user picture size

---

app/models/user.rb
lib/tasks/dev.rake

1. 修改demo rake bug
2. 將demo fake打包至一個任務(rails dev:fake_demo_all)中

修改demo rake bug,將其打包至一個任務中

---

lib/tasks/dev.rake

將user假資料名字修改成男女名字
